# Generated by Django 2.1.5 on 2019-02-15 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0002_auto_20190203_1052'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestM',
            new_name='TestInfo',
        ),
    ]
