# Generated by Django 2.1.5 on 2019-02-25 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0003_auto_20190215_0449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testinfo',
            old_name='NegMarks',
            new_name='NegativeMarks',
        ),
        migrations.RenameField(
            model_name='testinfo',
            old_name='PosMarks',
            new_name='PositiveMarks',
        ),
    ]
