# Generated by Django 2.1.5 on 2019-02-25 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0004_auto_20190225_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testinfo',
            old_name='NegativeMarks',
            new_name='NegMarks',
        ),
        migrations.RenameField(
            model_name='testinfo',
            old_name='PositiveMarks',
            new_name='PosMarks',
        ),
    ]
